# yaml-language-server: $schema=https://raw.githubusercontent.com/awslabs/goformation/v4/schema/cloudformation.schema.json
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  Static Website hosted on AWS, deployable by Github Actions via OIDC.
  
  Hosting:
  Private Bucket with Policy and OAC-enabled Distribution for authorized GetObject.

  Building:
  GitubRole trusts Github via OIDC to request tokens for the repository listed

Parameters:
  AppName: 
    Type: String
    Default: "cs-itp-ssg-cd"
    Description: "AppName, used for BucketName, lowercase only!"
  AuthorizedGithubRepository: 
    Type: String
    Default: "Codingschule/aws-astro-headless-cms-deployment"
  DomainName:
    Type: String
    Default: "example.com"
    Description: "Custom domain name for the CloudFront distribution"

Resources:
  MyWebBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AppName}-pub-dist-${AWS::Region}-${AWS::AccountId}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  MyOac:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "${AWS::StackName}-oac"
        Description: "OAC for CloudFront to access S3"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: "index.html"
        Aliases:
          - !Ref DomainName
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt MyWebBucket.RegionalDomainName
            OriginAccessControlId: !Ref MyOac
            S3OriginConfig:
              OriginAccessIdentity: ""
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          CachePolicyId: "658327ea-f89d-4fab-a63d-7e88639e58f6"
        ViewerCertificate:
          AcmCertificateArn: !Ref WebsiteCertificate
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        HttpVersion: http2

        PriceClass: PriceClass_100

  WebsiteCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      ValidationMethod: DNS

  BucketPolicyCloudFront:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MyWebBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowCloudFrontServicePrincipal
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: "s3:GetObject"
            Resource: !Sub "${MyWebBucket.Arn}/*"
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}"

  # GitHub Actions OIDC Role
  GitubRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AppName}-github-actions-role"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: # Indirect reference to GitHubOidcProvider with url https://token.actions.githubusercontent.com
              Federated: !Sub "arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com"
            Action: "sts:AssumeRoleWithWebIdentity"
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:sub: # several entries possible
                  - !Sub "repo:${AuthorizedGithubRepository}:ref:refs/heads/dev"
              StringEqualsIgnoreCase:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
      Policies:
        - PolicyName: OidcSafetyPolicy # by default, DENY ALL! ## change for role chaining
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: OidcSafeties
                Effect: Deny
                Action:
                  - sts:AssumeRole
                Resource: "*"
        - PolicyName: !Sub "${AppName}-GithubDeployPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket # for --delete to plan what to clean up?
                Resource:
                  - !GetAtt MyWebBucket.Arn
                  - !Sub "${MyWebBucket.Arn}/*"
              - Effect: Allow
                Action:
                  - cloudfront:CreateInvalidation
                Resource: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}"

  GitHubOidcProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1

Outputs:
  GithubS3BucketName:
    Value: !Sub "${MyWebBucket}" 
  GithubCloudfrontDistributionId:
    Value: !Sub "${CloudFrontDistribution}"
  GithubAwsRoleArn:
    Value: !Sub "arn:aws:iam::${AWS::AccountId}:role/${AppName}-github-actions-role" 
  GithubAwsRegion:
    Value: !Sub "${AWS::Region}" 
  CloudFrontDomainName:
    Value: !GetAtt CloudFrontDistribution.DomainName
  CustomDomainName:
    Value: !Ref DomainName
    Description: "Custom domain configured for CloudFront"
  CertificateArn:
    Value: !Ref WebsiteCertificate
    Description: "ACM Certificate ARN for custom domain"
  DnsRecord:
    Value: !Sub "${DomainName} CNAME ${CloudFrontDistribution.DomainName}"
    Description: "DNS CNAME record to create"
  DebugSyncCommand:
    Value: !Sub "aws s3 sync ./frontend/dist/ s3://${MyWebBucket} --delete --role-arn arn:aws:iam::${AWS::AccountId}:role/${AppName}-github-actions-role" 
  BlockedBucketWebsite:
    Value: !Sub "http://${MyWebBucket}.s3-website-${AWS::Region}.amazonaws.com" 
  BlockedBucketUrl:
    Value: !Sub "https://${MyWebBucket}.s3.${AWS::Region}.amazonaws.com"
